# Generated by Django 2.2.9 on 2020-01-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_draw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
